app_001/urls.py
from django.conf.urls import url
from app_001 import views


app_name = 'app_001'

urlpatterns = [
    url(r'^$',views.index,name='index'), 
    url(r'^register/$',views.register,name='register'), 
    url(r'^user_login/$',views.user_login,name='user_login'),
]

cart/urls.py
from django.conf.urls import url
from .views import view_cart, add_to_cart, adjust_cart

urlpatterns = [
    url(r'^$', view_cart, name='view_cart'),
    url(r'^add/(?P<id>\d+)', add_to_cart, name='add_to_cart'),
    url(r'^adjust/(?P<id>\d+)', adjust_cart, name='adjust_cart'),
]

checkout/urls.py
from django.conf.urls import url
from .views import checkout

urlpatterns = [
    url(r'^$', checkout, name='checkout'),
]

products/urls.py
from django.conf.urls import url, include
from .views import all_products

urlpatterns = [
    url(r'^$', all_products, name='products'),
]

app_001/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfileInfo(models.Model):
    
    user = models.OneToOneField(User,on_delete=models.PROTECT)

    def __str__(self):
        
        return self.user.username

cart/models.py
from django.db import models

# Create your models here.

checkout/models.py
from django.db import models
from products.models import Product

# Create your models here.
class Order(models.Model):
    full_name = models.CharField(max_length=50, blank=False)
    phone_number = models.CharField(max_length=20, blank=False)
    country = models.CharField(max_length=40, blank=False)
    postcode = models.CharField(max_length=20, blank=True)
    town_or_city = models.CharField(max_length=40, blank=False)
    street_address1 = models.CharField(max_length=40, blank=False)
    street_address2 = models.CharField(max_length=40, blank=False)
    county = models.CharField(max_length=40, blank=False)
    date = models.DateField()

    def __str__(self):
        return "{0}-{1}-{2}".format(self.id, self.date, self.full_name)


class OrderLineItem(models.Model):
    order = models.ForeignKey(Order, null=False, on_delete=models.PROTECT)
    product = models.ForeignKey(Product, null=False, on_delete=models.PROTECT)
    quantity = models.IntegerField(blank=False, )

    def __str__(self):
        return "{0} {1} @ {2}".format(
            self.quantity, self.product.name, self.product.price)

products/models.py
from django.db import models

# Create your models here.

class Product(models.Model):
    name = models.CharField(max_length=254, default='')
    description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    image = models.ImageField(upload_to='images')

    def __str__(self):
        return self.name

app_001/forms.py
from django import forms
from django.contrib.auth.models import User
from app_001.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ()

  

checkout/forms.py
from django import forms
from .models import Order


class MakePaymentForm(forms.Form):

    MONTH_CHOICES = [(i, i) for i in range(1, 12)]
    YEAR_CHOICES = [(i, i) for i in range(2019, 2036)]

    credit_card_number = forms.CharField(label='Credit card number', required=False)
    cvv = forms.CharField(label='Security code (CVV)', required=False)
    expiry_month = forms.ChoiceField(label='Month', choices=MONTH_CHOICES, required=False)
    expiry_year = forms.ChoiceField(label='Year', choices=YEAR_CHOICES, required=False)
    stripe_id = forms.CharField(widget=forms.HiddenInput)


class OrderForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = (
            'full_name', 'phone_number', 'country', 'postcode',
            'town_or_city', 'street_address1', 'street_address2',
            'county'
        )

app_001/views.py
from django.shortcuts import render
from app_001.forms import UserForm,UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse 
from django.contrib.auth.decorators import login_required
# Create your views here.

def index(request):
    return render(request,'app_001/index.html')

def shop(request):
    return render(request,'app_001/shop.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()

            # Registration Successful!
            registered = True

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors,profile_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    # Return back to the registration.html file page.
    return render(request,'app_001/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})

def user_login(request):
    
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("Account not active.")

        else:
            print("failed login.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'app_001/login.html', {})

cart/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def view_cart(request):
    return render(request, "app_001/cart.html")

@login_required
def add_to_cart(request, id):
    quantity = int(request.POST.get('quantity'))

    cart = request.session.get('cart', {})
    cart[id] = cart.get(id, quantity)

    request.session['cart'] = cart
    return redirect(reverse('products'))

@login_required
def adjust_cart(request, id):
    quantity = int(request.POST.get('quantity'))
    cart = request.session.get('cart', {})

    if quantity > 0:
        cart[id] = quantity
    else:
        cart.pop(id)
    
    request.session['cart'] = cart
    return redirect(reverse('view_cart'))

checkout/views.py
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import MakePaymentForm, OrderForm
from .models import OrderLineItem
from django.conf import settings
from django.utils import timezone
from products.models import Product
import stripe

# Create your views here.
stripe.api_key = settings.STRIPE_SECRET


@login_required()
def checkout(request):
    if request.method == "POST":
        order_form = OrderForm(request.POST)
        payment_form = MakePaymentForm(request.POST)

        if order_form.is_valid() and payment_form.is_valid():
            order = order_form.save(commit=False)
            order.date = timezone.now()
            order.save()

            cart = request.session.get('cart', {})
            total = 0
            for id, quantity in cart.items():
                product = get_object_or_404(Product, pk=id)
                total += quantity * product.price
                order_line_item = OrderLineItem(
                    order=order,
                    product=product,
                    quantity=quantity
                )
                order_line_item.save()
            
            try:
                customer = stripe.Charge.create(
                    amount=int(total * 100),
                    currency="GBP",
                    description=request.user.email,
                    card=payment_form.cleaned_data['stripe_id']
                )
            except stripe.error.CardError:
                messages.error(request, "Your card was declined!")
            
            if customer.paid:
                messages.error(request, "You have successfully paid")
                request.session['cart'] = {}
                return redirect(reverse('products'))
            else:
                messages.error(request, "Unable to take payment")
        else:
            print(payment_form.errors)
            messages.error(request, "We were unable to take a payment with that card!")
    else:
        payment_form = MakePaymentForm()
        order_form = OrderForm()
    
    return render(request, "app_001/checkout.html", {"order_form": order_form, "payment_form": payment_form, "publishable": settings.STRIPE_PUBLISHABLE})

products/views.py
from django.shortcuts import render
from .models import Product
# Create your views here.

def all_products(request):
    products = Product.objects.all()
    return render(request, "app_001/products.html", {'products': products})
     

templates/app_001/base_001.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

    <head>

        <meta charset="utf-8">
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>Paddy Boyle | Property Photography</title>

        <link
            href="{% static "vendor/fontawesome-free/css/all.min.css" %}"
            rel="stylesheet"
            type="text/css">
        <link
            href="https://fonts.googleapis.com/css?family=Montserrat:400,700"
            rel="stylesheet"
            type="text/css">
        <link
            href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic"
            rel="stylesheet"
            type="text/css">
        <link
            href="https://fonts.googleapis.com/css?family=Quicksand:400,600,700&display=swap"
            rel="stylesheet">
        <link href="{% static "css/freelancer.min.css" %}" rel="stylesheet">
        <link
            rel="stylesheet"
            href="{% static 'font-awesome/css/font-awesome.min.css' %}">
        <script
            type="text/javascript"
            src="https://cdn.jsdelivr.net/npm/emailjs-com@2.3.2/dist/email.min.js"></script>
        <script type="text/javascript">
            (function () {
                emailjs.init("user_KZZz5GUr7LB1TlhkKGwj9");
            })();
        </script>

    </head>

    <body id="page-top">

        <!-- Navigation -->
        <nav
            class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top"
            id="mainNav">
            <div class="container">
                <a class="navbar-brand js-scroll-trigger" href="#page-top">Paddy Boyle |
                    <span>Photo Archive</span></a>
                <button
                    class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded"
                    type="button"
                    data-toggle="collapse"
                    data-target="#navbarResponsive"
                    aria-controls="navbarResponsive"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item mx-0 mx-lg-1">
                            <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#about">About</a>
                        </li>
                        <li class="nav-item mx-0 mx-lg-1">
                            <a
                                class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger"
                                href="#portfolio">Portfolio</a>
                        </li>
                        <li class="nav-item mx-0 mx-lg-1">
                            <a
                                class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger"
                                href="{% url 'products' %}">Shop</a>
                        </li>
                        <li class="nav-item mx-0 mx-lg-1">
                            <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#contact">Contact</a>
                        </li>

                        {% if user.is_authenticated %}

                            <li class="nav-item mx-0 mx-lg-1">
                                <a
                                    class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger"
                                    onmouseover="myFunction()"
                                    href="{% url 'logout' %}">Logout</a>
                            </li>
                            <script>
                                var flag = false;

                                function myFunction() {
                                    if (!flag) {
                                        alert("Warning! All shopping cart data will be lost if you logout.");
                                        flag = true;
                                    }
                                }
                            </script>

                        {% else %}

                            <li class="nav-item mx-0 mx-lg-1">
                                <a
                                    class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger"
                                    href="{% url 'app_001:user_login' %}">Login</a>
                            </li>

                        {% endif %}

                    </ul>
                </div>
            </div>
        </nav>

        <!-- /Navigation -->

        {% block body_block %}{% endblock %}

        <!-- Footer -->
        <footer class="footer text-center">
            <div class="container">
                <div class="row">

                    <!-- Footer Location -->
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <h4 class="location text-uppercase mb-4">Location</h4>
                        <p class="lead mb-0">21 Dudley Road, Hastings, East Sussex, TN35 5JP</p>
                    </div>

                    <!-- Footer Social Icons -->
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <h4 class="location text-uppercase mb-4">Around the Web</h4>
                        <a
                            class="btn btn-outline-light btn-social mx-1"
                            href="https://www.facebook.com/paddy.boyle.1614">
                            <i class="fab fa-fw fa-facebook-f"></i>
                        </a>

                        <a
                            class="btn btn-outline-light btn-social mx-1"
                            href="https://www.linkedin.com/in/pboylephotography/">
                            <i class="fab fa-fw fa-linkedin-in"></i>
                        </a>

                    </div>

                    <!-- Footer About Text -->
                    <div class="col-lg-4">
                        <h4 class="location text-uppercase mb-4">Contact</h4>
                        <p class="lead mb-0">01424 444039
                            <br>
                            07963110227
                        </p>
                    </div>

                </div>
            </div>
        </footer>

        <!-- /Footer -->

        <!-- Copyright Section -->
        <section class="copyright py-4 text-center text-white">
            <div class="container">
                <small>Copyright &copy; www.pboylephotoarchive.com 2019</small>
            </div>
        </section>

        <div class="scroll-to-top d-lg-none position-fixed ">
            <a
                class="js-scroll-trigger d-block text-center text-white rounded"
                href="#page-top">
                <i class="fa fa-chevron-up"></i>
            </a>
        </div>

         <!-- /Copyright Section -->

        <!-- Bootstrap core JavaScript -->
        <script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
        <script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

        <!-- Plugin JavaScript -->
        <script src="{% static "vendor/jquery-easing/jquery.easing.min.js" %}"></script>

        <!-- Contact Form JavaScript -->
        <script src="{% static "js/jqBootstrapValidation.js" %}"></script>
        <script src="{% static "js/contact_me.js" %}"></script>

        <!-- Custom scripts for this template -->
        <script src="{% static "js/freelancer.min.js" %}"></script>

        <script src="{% static "js/sendEmail.js" %}"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    </body>

</html>

templates/app_001/base_002.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

    <head>

        <meta charset="utf-8">
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>Paddy Boyle | Property Photography</title>

        <link
            href="{% static "vendor/fontawesome-free/css/all.min.css" %}"
            rel="stylesheet"
            type="text/css">
        <link
            href="https://fonts.googleapis.com/css?family=Montserrat:400,700"
            rel="stylesheet"
            type="text/css">
        <link
            href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic"
            rel="stylesheet"
            type="text/css">
        <link
            href="https://fonts.googleapis.com/css?family=Quicksand:400,600,700&display=swap"
            rel="stylesheet">
        <link href="{% static "css/freelancer.min.css" %}" rel="stylesheet">
        <link href="{% static "css/custom.css" %}" rel="stylesheet">
        <link
            rel="stylesheet"
            href="{% static 'font-awesome/css/font-awesome.min.css' %}">

        <script
            type="text/javascript"
            src="https://cdn.jsdelivr.net/npm/emailjs-com@2.3.2/dist/email.min.js"></script>
        <script type="text/javascript">
            (function () {
                emailjs.init("user_KZZz5GUr7LB1TlhkKGwj9");
            })();
        </script>

    </head>

    <body id="page-top">

        <!-- Navigation -->

        <nav
            class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top"
            id="mainNav">
            <div class="container">
                <a class="navbar-brand js-scroll-trigger" href="{% url 'app_001:index' %}">Paddy Boyle |
                    <span>Photo Archive</span></a>
                <button
                    class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded"
                    type="button"
                    data-toggle="collapse"
                    data-target="#navbarResponsive"
                    aria-controls="navbarResponsive"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item mx-0 mx-lg-1">
                            <a
                                class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger"
                                href="{% url 'index' %}">&larr; Back to home</a>
                        </li>
                        {% if user.is_authenticated %}

                            <li class="nav-item mx-0 mx-lg-1">
                                <a
                                    class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger"
                                    onmouseover="myFunction()"
                                    href="{% url 'logout' %}">Logout</a>
                            </li>
                            <script>
                                var flag = false;

                                function myFunction() {
                                    if (!flag) {
                                        alert("Warning! All shopping cart data will be lost if you logout.");
                                        flag = true;
                                    }
                                }
                            </script>

                        {% else %}

                            <li class="nav-item mx-0 mx-lg-1">
                                <a
                                    class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger"
                                    href="{% url 'app_001:user_login' %}">Login</a>
                            </li>

                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        <!-- /Navigation -->

        {% block body_block %}{% endblock %}

        <!-- Footer -->
        <footer class="footer text-center">
            <div class="container">
                <div class="row">

                    <!-- Footer Location -->
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <h4 class="location text-uppercase mb-4">Location</h4>
                        <p class="lead mb-0">21 Dudley Road, Hastings, East Sussex, TN35 5JP</p>
                    </div>

                    <!-- Footer Social Icons -->
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <h4 class="location text-uppercase mb-4">Around the Web</h4>
                        <a
                            class="btn btn-outline-light btn-social mx-1"
                            href="https://www.facebook.com/paddy.boyle.1614">
                            <i class="fab fa-fw fa-facebook-f"></i>
                        </a>

                        <a
                            class="btn btn-outline-light btn-social mx-1"
                            href="https://www.linkedin.com/in/pboylephotography/">
                            <i class="fab fa-fw fa-linkedin-in"></i>
                        </a>

                    </div>

                    <!-- Footer About Text -->
                    <div class="col-lg-4">
                        <h4 class="location text-uppercase mb-4">Contact</h4>
                        <p class="lead mb-0">01424 444039
                            <br>
                            07963110227
                        </p>
                    </div>

                </div>
            </div>
        </footer>

        <!-- /Footer -->

        <!-- Copyright Section -->
        <section class="copyright py-4 text-center text-white">
            <div class="container">
                <small>Copyright &copy; www.pboylephotoarchive.com 2019</small>
            </div>
        </section>

        <div class="scroll-to-top d-lg-none position-fixed ">
            <a
                class="js-scroll-trigger d-block text-center text-white rounded"
                href="#page-top">
                <i class="fa fa-chevron-up"></i>
            </a>
        </div>

        <!-- /Copyright Section -->

        <!-- Bootstrap core JavaScript -->
        <script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
        <script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

        <!-- Plugin JavaScript -->
        <script src="{% static "vendor/jquery-easing/jquery.easing.min.js" %}"></script>

        <!-- Contact Form JavaScript -->
        <script src="{% static "js/jqBootstrapValidation.js" %}"></script>
        <script src="{% static "js/contact_me.js" %}"></script>

        <!-- Custom scripts for this template -->
        <script src="{% static "js/freelancer.min.js" %}"></script>

        <script src="{% static "js/sendEmail.js" %}"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    </body>

</html>

templates/app_001/cart.html
{% extends 'app_001/base_004.html' %}
{% block body_block %}

    <section class="page-section about" id="architecture">
        <div class="container">

            <!-- Heading -->

            <h2
                class="cat-heading page-section-heading text-center text-uppercase text-secondary mb-0">Shopping Cart</h2>

            <!-- /Heading -->

            <!-- Icon Divider -->
            
            <div class="divider-custom">
                <div class="divider-custom-line"></div>

            </div><br><br>

            <!-- Icon Divider -->

            <!-- Cart contents -->

            <div class="container">
                <div class="row">
                    <figure class="col-md-12">
                        <p>Total</p>
                        <p>
                            <span class="glyphicon glyphicon-euro " aria-hidden="true"></span>{{ total }}</p>
                        <a href="{% url 'checkout' %}" class="btn btn-success" role="button">
                            <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>Checkout</a>
                    </figure>
                </div>
            </div>

            <div class="row">
                {% for item in cart_items %}
                    <figure class="col-xs-12 col-sm-12 col-md-6 col-lg-4 col-xl-4">
                        <div id="wrapper-002">
                            <a href=""></a>
                            <div
                                class="product"
                                style="background-image: url('{{ MEDIA_URL }}{{ item.product.image }}')"></div>
                            <br>

                            <h3 class="text-002 lead">{{item.product.name}}</h3>
                            <p class="product-description">{{ item.product.description }}</p>
                            <p>{{ item.product.price }}</p>
                            <p>
                                <div class="input-group-addon">Qty:
                                    {{item.quantity}}</div><br>

                                <form
                                    class="form-inline-001 "
                                    method="post"
                                    action="{% url 'adjust_cart' item.id %}">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <label for="exampleInputAmount" class="sr-only">New Qty</label>
                                        <div class="input-group">

                                            <input
                                                name="quantity"
                                                type="number"
                                                min="0"
                                                max="999"
                                                class="form-control"
                                                placeholder="New Quantity"><br><br>

                                        </div>
                                    </div>
                                    <button type="submit" class="btn btn-success">
                                        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>Amend</button>
                                </form>

                            </div>

                        </figure>
                    {% endfor %}

                </div>

                <!-- /Cart contents -->

            </div>
        </section>

    {% endblock %}

templates/app_001/catagory_001.html
{% extends 'app_001/base_003.html' %}
{% block body_block %}

    <section class="page-section about" id="architecture">
        <div class="container">

            <!-- Heading -->

            <h2
                class="cat-heading page-section-heading text-center text-uppercase text-secondary mb-0">People</h2>
            
            <!-- /Heading -->

            <!-- Icon Divider -->

            <div class="divider-custom">
                <div class="divider-custom-line"></div>

            </div><br><br>

            <!-- /Icon Divider -->

            <!-- images -->

            <div class="row">
                {% for images in category_001 %}
                    <figure class="col-xs-12 col-sm-12 col-md-6 col-lg-4 col-xl-4">
                        <div id="wrapper-002">
                            <a href="{{images.url}}">
                                <div
                                    class="product"
                                    style="background-image: url('{{ MEDIA_URL }}{{ images.image }}')"></div>
                            </a>
                            <br>
                            <h3 class="text-002 lead">{{images.name}}</h3>

                        </div>

                    </figure>
                {% endfor %}
            </div>

            <!-- /images -->

            <br><br>
        </div>
    </section>

{% endblock %}

templates/app_001/login.html
{% extends 'app_001/base_002.html' %}
{% block body_block %}

    <section class="page-section about" id="about">
        <div class="container">

            

            <br>
                <br>

                    <!-- About Section Content -->
                    <div class="row">

                        <div class="container text-center">
                            <div class="jumbotron">
                                <h1 class="page-section-heading text-center text-uppercase text-secondary mb-0">Please Login</h1>
                                <br><br>

                                    <form method="post" action="{% url 'app_001:user_login' %}">
                                        {% csrf_token %}
                                        <label for="username">Username:</label>
                                        <input type="text" name="username" placeholder="Username">
                                            <label for="password"></label>
                                            <input type="password" name="password">

                                                <input class="btn btn-success" type="submit" name="" value="Login"></form>
                                                <br>
                                                    <p>Not regestered?</p>
                                                    <a href="{% url 'register' %}">Please regester here</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </section>

                            {% endblock %}